name: Upload Python Package to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウトする
      # See: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Python のランタイムをセットアップする
      # See: https://github.com/actions/setup-python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      # Poetryのインストール
      - name: Install Poetry
        run: |
          pip install poetry
      # パッケージのビルドとPyPIへのアップロード
      - name: Build and publish
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_API_TOKEN
          poetry publish --build
