name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウトする
      # See: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Python のランタイムをセットアップする
      # バージョンは `strategy.matrix` に並べたものを指定する
      # See: https://github.com/actions/setup-python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      # Poetryのインストール
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry twine
      # パッケージのビルドとPyPIへのアップロード
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry publish --build --username $TWINE_USERNAME --password $TWINE_PASSWORD
